name: Test installers
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-installers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - "centos:8"
          - "fedora:34"
          - "debian:bullseye"
          - "ubuntu:focal"
        type: [ live, release ]
        version: ['1.10', '2.8']
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2

    - name: Setup Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Installer
      run: ./mkinstaller.py ${{ matrix.type }} ${{ matrix.version }}

    - name: Set up Tarantool in docker
      run: docker run --rm -v $(pwd):/app ${{ matrix.image }} sh -c "bash /app/installer.sh"
